# To build a Docker image from this file, run from the root directory:

# docker build -f deployment/Dockerfile-innkeeper -t peerprep-innkeeper-service .

# Intermediate image for building the Next app

FROM node:18.17.1

# Environment variables

ENV APP_ROOT /innkeeper

# Copy source code into container

RUN mkdir --parents $APP_ROOT
WORKDIR $APP_ROOT
COPY innkeeper .

# Install dependencies

RUN yarn install --frozen-lockfile

# Build app

RUN yarn build

# Expose port

EXPOSE 4100

# Final image for running the Socket.IO app

CMD ["yarn", "start"]
