# To build a Docker image from this file, run from the root directory:

# docker build -f deployment/Dockerfile-executor -t peerprep-executor .

FROM opensuse/tumbleweed

# Environment variables

ENV APP_ROOT /executor

WORKDIR $APP_ROOT
COPY executor .

RUN groupadd -g 1300 -r peerprep && useradd -g 1300 -u 1500 -r executor

RUN zypper refresh
RUN zypper install -t pattern -y devel_C_C++
RUN zypper install -y cmake
RUN zypper install -y java-11-openjdk-devel

RUN cmake -DCMAKE_BUILD_TYPE=Release -S . -B ./build
RUN cmake --build ./build --config Release
RUN cp ./build/executor ./executor

EXPOSE 9000

CMD ["./executor"]
